"""Public contract surface for the typed ETABS gateway."""

from .com_apartment import WindowsCOMApartment
from .connection import (
    DEFAULT_ETABS_PROG_IDS,
    ReadOnlyETABSConnection,
)
from .contracts import (
    AttachMode,
    ConnectionDiagnostics,
    ConnectionRequest,
    DiagnosticEvent,
    DiagnosticSeverity,
    ETABSAttachment,
    ETABSApplicationInfo,
    ETABSGatewayContext,
    ETABSModelContext,
    ETABSUnitContext,
    GatewayHealth,
    GatewayState,
    HealthStatus,
)
from .errors import (
    ETABSCOMFinalizationError,
    ETABSCOMInitializationError,
    ETABSAttachError,
    ETABSCallError,
    ETABSGatewayError,
    ETABSModelLockReadError,
    ETABSModelPathReadError,
    ETABSUnitsReadError,
    ETABSModelUnavailableError,
    ETABSNotRunningError,
    ETABSFixtureValidationError,
    ETABSSessionCloseError,
    ETABSSessionStateError,
    ETABSThreadViolationError,
    ETABSTimeoutError,
    ETABSVersionReadError,
    ETABSWorkerClosedError,
    ETABSWorkerStartError,
)
from .replay import (
    ETABSGatewayFixture,
    FIXTURE_SCHEMA_VERSION,
    FIXTURE_TYPE,
    FixtureReplayProvider,
    build_gateway_context_fixture,
    canonical_gateway_context_fixture_json,
    context_from_payload,
    context_to_payload,
    dump_gateway_context_fixture,
    load_gateway_context_fixture,
    parse_gateway_context_fixture,
)
from .session import ETABSGatewaySession
from .worker import DedicatedSTAWorker, WorkerState

__all__ = [
    "DEFAULT_ETABS_PROG_IDS",
    "ReadOnlyETABSConnection",
    "WindowsCOMApartment",
    "AttachMode",
    "ConnectionDiagnostics",
    "ConnectionRequest",
    "DiagnosticEvent",
    "DiagnosticSeverity",
    "ETABSAttachment",
    "ETABSApplicationInfo",
    "ETABSGatewayContext",
    "ETABSModelContext",
    "ETABSUnitContext",
    "GatewayHealth",
    "GatewayState",
    "HealthStatus",
    "ETABSCOMFinalizationError",
    "ETABSCOMInitializationError",
    "ETABSAttachError",
    "ETABSCallError",
    "ETABSGatewayError",
    "ETABSModelLockReadError",
    "ETABSModelPathReadError",
    "ETABSUnitsReadError",
    "ETABSModelUnavailableError",
    "ETABSNotRunningError",
    "ETABSFixtureValidationError",
    "ETABSSessionCloseError",
    "ETABSSessionStateError",
    "ETABSThreadViolationError",
    "ETABSTimeoutError",
    "ETABSVersionReadError",
    "ETABSWorkerClosedError",
    "ETABSWorkerStartError",
    "ETABSGatewayFixture",
    "FIXTURE_SCHEMA_VERSION",
    "FIXTURE_TYPE",
    "FixtureReplayProvider",
    "build_gateway_context_fixture",
    "canonical_gateway_context_fixture_json",
    "context_from_payload",
    "context_to_payload",
    "dump_gateway_context_fixture",
    "load_gateway_context_fixture",
    "parse_gateway_context_fixture",
    "ETABSGatewaySession",
    "DedicatedSTAWorker",
    "WorkerState",
]
