"""Public contract surface for the typed ETABS gateway."""

from .com_apartment import WindowsCOMApartment
from .connection import (
    DEFAULT_ETABS_PROG_IDS,
    ReadOnlyETABSConnection,
)
from .contracts import (
    AttachMode,
    ConnectionDiagnostics,
    ConnectionRequest,
    DiagnosticEvent,
    DiagnosticSeverity,
    ETABSAttachment,
    ETABSApplicationInfo,
    ETABSGatewayContext,
    ETABSModelContext,
    ETABSUnitContext,
    GatewayHealth,
    GatewayState,
    HealthStatus,
)
from .errors import (
    ETABSCOMFinalizationError,
    ETABSCOMInitializationError,
    ETABSAttachError,
    ETABSCallError,
    ETABSGatewayError,
    ETABSModelLockReadError,
    ETABSModelPathReadError,
    ETABSUnitsReadError,
    ETABSModelUnavailableError,
    ETABSNotRunningError,
    ETABSThreadViolationError,
    ETABSTimeoutError,
    ETABSVersionReadError,
    ETABSWorkerClosedError,
    ETABSWorkerStartError,
)
from .worker import DedicatedSTAWorker, WorkerState

__all__ = [
    "DEFAULT_ETABS_PROG_IDS",
    "ReadOnlyETABSConnection",
    "WindowsCOMApartment",
    "AttachMode",
    "ConnectionDiagnostics",
    "ConnectionRequest",
    "DiagnosticEvent",
    "DiagnosticSeverity",
    "ETABSAttachment",
    "ETABSApplicationInfo",
    "ETABSGatewayContext",
    "ETABSModelContext",
    "ETABSUnitContext",
    "GatewayHealth",
    "GatewayState",
    "HealthStatus",
    "ETABSCOMFinalizationError",
    "ETABSCOMInitializationError",
    "ETABSAttachError",
    "ETABSCallError",
    "ETABSGatewayError",
    "ETABSModelLockReadError",
    "ETABSModelPathReadError",
    "ETABSUnitsReadError",
    "ETABSModelUnavailableError",
    "ETABSNotRunningError",
    "ETABSThreadViolationError",
    "ETABSTimeoutError",
    "ETABSVersionReadError",
    "ETABSWorkerClosedError",
    "ETABSWorkerStartError",
    "DedicatedSTAWorker",
    "WorkerState",
]
